-- 사용자
CREATE TABLE USERS
(
    USER_ID     VARCHAR(30)  NOT NULL PRIMARY KEY,
    PASSWORD    LONGTEXT     NOT NULL,
    OTP_SCT_KEY VARCHAR(300) NULL,
    USER_NM     VARCHAR(100) NOT NULL,
    EMAIL       VARCHAR(100) NOT NULL,
    CRT_ID      VARCHAR(30)  NOT NULL,
    CRT_DT      DATETIME(0)  NULL,
    MDF_ID      VARCHAR(30)  NOT NULL,
    MDF_DT      DATETIME(0)  NULL
);

-- 접속 이력
CREATE TABLE USER_HST
(
    HST_ID  BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    HST_DT  DATETIME(0) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);
